---
title: "Архитектура Компьютеров и операционные системы"
author: "МВЕТУВОП ФОНГАНГ ДЖУЛС ФЕРРИ"
date: "2026-03-07"
format:
  pdf:
    toc: true
    number-sections: true
    pdf-engine: xelatex
    mainfont: "FreeSerif"
    sansfont: "FreeSans"
    monofont: "FreeMono"
    lang: ru
  docx:
    toc: true
    number-sections: true
---

\begin{center}
РОССИЙСКИЙ УНИВЕРСИТЕТ ДРУЖБЫ НАРОДОВ \\
Факультет физико-математических и естественных наук \\
Кафедра: Бизнес Информатика \\
\vspace{3cm}
\textbf{Архитектура Компьютеров и операционные системы} \\
\vspace{2cm}
\textbf{Лабораторная работа №4 :} \\
\textbf{Продвинутое использование git} \\
\vspace{2cm}
\begin{flushright}
\textbf{МВЕТУВОП ФОНГАНГ ДЖУЛС ФЕРРИ} \\
\textbf{1132255560} \\
\textbf{Группа: НБИбд-02-25}
\end{flushright}
\end{center}
\newpage

# Лабораторная работа №4: Продвинутое использование git

## Цель работы

Получение навыков правильной работы с репозиториями git.

## Теоретические сведения

### Рабочий процесс Gitflow

Рабочий процесс Gitflow Workflow. Будем описывать его с использованием пакета git-flow.

#### Общая информация

Gitflow Workflow опубликована и популяризована Винсентом Дриссеном. Gitflow Workflow предполагает выстраивание строгой модели ветвления с учётом выпуска проекта. Данная модель отлично подходит для организации рабочего процесса на основе релизов.

Работа по модели Gitflow включает создание отдельной ветки для исправлений ошибок в рабочей среде.

Последовательность действий при работе по модели Gitflow:

1. Из ветки `master` создаётся ветка `develop`.
2. Из ветки `develop` создаётся ветка `release`.
3. Из ветки `develop` создаются ветки `feature`.
4. Когда работа над веткой `feature` завершена, она сливается с веткой `develop`.
5. Когда работа над веткой релиза `release` завершена, она сливается в ветки `develop` и `master`.
6. Если в `master` обнаружена проблема, из `master` создаётся ветка `hotfix`.
7. Когда работа над веткой исправления `hotfix` завершена, она сливается в ветки `develop` и `master`.

#### Процесс работы с Gitflow

**Основные ветки (master) и ветки разработки (develop)**

Для фиксации истории проекта в рамках этого процесса вместо одной ветки `master` используются две ветки. В ветке `master` хранится официальная история релиза, а ветка `develop` предназначена для объединения всех функций. Кроме того, для удобства рекомендуется присваивать всем коммитам в ветке `master` номер версии.

При использовании библиотеки расширений git-flow нужно инициализировать структуру в существующем репозитории:

```bash
git flow init
